server:
  port: 8083
  wait-time-in-ms-when-sync-wmpty: 3000

spring: 
  spring:
    profiles:
      active: native

  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.2
      database: salesdb
      auto-index-creation: true

  
application:
  productService:
    url: http://localhost:8082
    endpointConsultProduct: ${application.product-service.url}/produto
  clientService:
    url: http://localhost:8081
    endpointConsultClient: ${application.client-service.url}/cliente/isCadastrado/{id}
application-version: 2.0 